#import <Foundation/Foundation.h>

// Generated by React Native codegen from src/specs/NativeRnSqlConnect.ts.
// codegenConfig.name in package.json decides the header name.
#import <RNSqlConnectSpec/RNSqlConnectSpec.h>

NS_ASSUME_NONNULL_BEGIN

/// TurboModule shim. Argument marshalling only; the Data Connect work lives in
/// RnSqlConnectCore.swift.
@interface RnSqlConnect : NativeRnSqlConnectSpecBase <NativeRnSqlConnectSpec>
@end

NS_ASSUME_NONNULL_END
