import type { ParsedOperation, ParsedSdk } from './parse'

const HEADER = `/**
 * Generated by rn-sql-connect-codegen. Do not edit.
 *
 * Function names match the Firebase-generated JavaScript SDK on purpose, so
 * migrating a call site is only a change of import path.
 */`

const capitalize = (value: string): string => value.charAt(0).toUpperCase() + value.slice(1)

const dataType = (operation: ParsedOperation): string => `${capitalize(operation.name)}Data`
const variablesType = (operation: ParsedOperation): string =>
  `${capitalize(operation.name)}Variables`

const emitQuery = (operation: ParsedOperation): string => {
  const data = dataType(operation)
  if (!operation.hasVariables) {
    return `export function ${operation.name}(
  dc: SqlConnect = defaultInstance(),
  options?: ExecuteQueryOptions,
): Promise<QueryResult<${data}>> {
  return executeQuery<${data}>(dc, '${operation.operationName}', undefined, options)
}

export function subscribe${capitalize(operation.name)}(
  dc: SqlConnect,
  observer: SubscriptionObserver<${data}>,
): Unsubscribe {
  return subscribe<${data}>(dc, '${operation.operationName}', undefined, observer)
}`
  }

  const vars = variablesType(operation)
  const varsParam = operation.variablesOptional ? `vars?: ${vars}` : `vars: ${vars}`
  return `export function ${operation.name}(
  dc: SqlConnect,
  ${varsParam},
  options?: ExecuteQueryOptions,
): Promise<QueryResult<${data}>> {
  return executeQuery<${data}, ${vars}>(dc, '${operation.operationName}', vars, options)
}

export function subscribe${capitalize(operation.name)}(
  dc: SqlConnect,
  ${varsParam},
  observer: SubscriptionObserver<${data}> = {},
): Unsubscribe {
  return subscribe<${data}, ${vars}>(dc, '${operation.operationName}', vars, observer)
}`
}

const emitMutation = (operation: ParsedOperation): string => {
  const data = dataType(operation)
  if (!operation.hasVariables) {
    return `export function ${operation.name}(
  dc: SqlConnect = defaultInstance(),
): Promise<MutationResult<${data}>> {
  return executeMutation<${data}>(dc, '${operation.operationName}')
}`
  }
  const vars = variablesType(operation)
  const varsParam = operation.variablesOptional ? `vars?: ${vars}` : `vars: ${vars}`
  return `export function ${operation.name}(
  dc: SqlConnect,
  ${varsParam},
): Promise<MutationResult<${data}>> {
  return executeMutation<${data}, ${vars}>(dc, '${operation.operationName}', vars)
}`
}

export const emitIndex = (sdk: ParsedSdk): string => {
  const { connectorConfig, operations } = sdk
  const body = operations
    .map(operation => (operation.kind === 'query' ? emitQuery(operation) : emitMutation(operation)))
    .join('\n\n')

  return `${HEADER}
/* eslint-disable */
import {
  executeMutation,
  executeQuery,
  getSqlConnect,
  subscribe,
  type ConnectorConfig,
  type ExecuteQueryOptions,
  type MutationResult,
  type QueryResult,
  type SqlConnect,
  type SubscriptionObserver,
  type Unsubscribe,
} from 'rn-sql-connect'

import type * as Types from './types'

export * from './types'

export const connectorConfig: ConnectorConfig = {
  connector: '${connectorConfig.connector}',
  serviceId: '${connectorConfig.service}',
  location: '${connectorConfig.location}',
}

/**
 * Instance used when a call site omits one.
 *
 * Handy for operations without variables. Anything that needs custom settings
 * or a non-default Firebase app should pass its own handle.
 */
export const defaultInstance = (): SqlConnect => getSqlConnect(connectorConfig)

${operations
  .flatMap(operation => {
    const names = [`${capitalize(operation.name)}Data`]
    if (operation.hasVariables) {
      names.push(`${capitalize(operation.name)}Variables`)
    }
    return names
  })
  .map(name => `type ${name} = Types.${name}`)
  .join('\n')}

${body}
`
}

export const emitTypes = (types: string): string => `${HEADER}
/* eslint-disable */

${types}
`
