export type OperationKind = 'query' | 'mutation'

export type ParsedOperation = {
  /** Exported name in the generated SDK, e.g. `listMovies`. */
  name: string
  /** Server side operation name, e.g. `ListMovies`. */
  operationName: string
  kind: OperationKind
  hasVariables: boolean
  /** Whether every variable is optional, so the argument can be omitted. */
  variablesOptional: boolean
}

export type ParsedConnectorConfig = {
  connector: string
  service: string
  location: string
}

export type ParsedSdk = {
  connectorConfig: ParsedConnectorConfig
  operations: ParsedOperation[]
  types: string
}

export class CodegenError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'CodegenError'
  }
}

const REF_BLOCK = /export const (\w+)Ref = \(([^)]*)\) => \{([\s\S]*?)\n\}/g
const OPERATION_NAME = /(\w+)Ref\.operationName = '([^']+)'/g

/**
 * Reads the ESM bundle of a Firebase-generated JavaScript SDK.
 *
 * Parsing generated JavaScript is deliberate. That bundle is the only artefact
 * that states an operation's server side name, and it is regenerated by the
 * same CLI version the app already runs, so it cannot drift from the types.
 *
 * Every assumption below is checked and the whole run fails when one breaks.
 * Silently emitting a partial SDK would leave callers with functions that do
 * not exist, found only at runtime.
 */
export const parseEsm = (source: string): Omit<ParsedSdk, 'types'> => {
  const operationNames = new Map<string, string>()
  OPERATION_NAME.lastIndex = 0
  for (let match = OPERATION_NAME.exec(source); match !== null; match = OPERATION_NAME.exec(source)) {
    operationNames.set(match[1], match[2])
  }

  const operations: ParsedOperation[] = []
  REF_BLOCK.lastIndex = 0
  for (let match = REF_BLOCK.exec(source); match !== null; match = REF_BLOCK.exec(source)) {
    const [, name, args, body] = match
    const operationName = operationNames.get(name)
    if (!operationName) {
      throw new CodegenError(
        `Found ref "${name}Ref" but no matching "${name}Ref.operationName = ..." assignment. ` +
          'The generated SDK format changed; rn-sql-connect-codegen needs updating.',
      )
    }

    const isQuery = body.includes('queryRef(')
    const isMutation = body.includes('mutationRef(')
    if (isQuery === isMutation) {
      throw new CodegenError(
        `Could not tell whether "${name}" is a query or a mutation. ` +
          'The generated SDK format changed; rn-sql-connect-codegen needs updating.',
      )
    }

    // Operations without variables are emitted as `(dc) => ...`, operations
    // with variables as `(dcOrVars, vars) => ...`.
    const hasVariables = args.includes(',')
    // The fourth argument of validateArgs is the "variables are required" flag.
    const validateArgs = /validateArgs\([^)]*?,\s*(true|false)\s*\)/.exec(body)
    const variablesOptional = hasVariables ? validateArgs?.[1] !== 'true' : true

    operations.push({ name, operationName, kind: isQuery ? 'query' : 'mutation', hasVariables, variablesOptional })
  }

  if (operations.length === 0) {
    throw new CodegenError(
      'No operations found in the generated SDK. Point --in at the directory that contains ' +
        'index.d.ts and esm/index.esm.js.',
    )
  }

  const connectorConfig = parseConnectorConfig(source)
  return { connectorConfig, operations }
}

const parseConnectorConfig = (source: string): ParsedConnectorConfig => {
  const block = /export const connectorConfig = \{([\s\S]*?)\}/.exec(source)
  if (!block) {
    throw new CodegenError('Could not find `export const connectorConfig` in the generated SDK.')
  }
  const read = (key: string): string => {
    const match = new RegExp(`${key}:\\s*'([^']*)'`).exec(block[1])
    if (!match) {
      throw new CodegenError(`connectorConfig is missing "${key}".`)
    }
    return match[1]
  }
  return { connector: read('connector'), service: read('service'), location: read('location') }
}

const SKIP_PREFIXES = ['export const ', 'export function ', 'import ', 'declare ']

/**
 * Types that only exist in the web SDK. Anything still mentioning one of these
 * after filtering means the emitted SDK would need the `firebase` package,
 * which defeats the purpose of moving to native.
 */
const WEB_SDK_TYPES = [
  'QueryRef',
  'MutationRef',
  'QueryPromise',
  'MutationPromise',
  'DataConnect',
  'ConnectorConfig',
  'ExecuteQueryOptions',
]

/**
 * Keeps the data and variables interfaces from `index.d.ts` and drops
 * everything tied to the web SDK.
 *
 * Copying rather than re-exporting keeps the emitted SDK free of any dependency
 * on the `firebase` package, which is the point of moving to native.
 */
export const extractTypes = (declaration: string): string => {
  const lines = declaration.split('\n')
  const kept: string[] = []
  let depth = 0
  let skipping = false

  for (const line of lines) {
    const trimmed = line.trim()

    if (depth === 0) {
      if (trimmed.length === 0) {
        kept.push('')
        continue
      }
      // Ref interfaces return QueryRef/MutationRef from the web SDK. The CLI
      // emits some of them without `export`, so both forms have to be caught.
      const isRefInterface = /^(export )?interface \w+Ref\b/.test(trimmed)
      skipping = isRefInterface || SKIP_PREFIXES.some(prefix => trimmed.startsWith(prefix))
    }

    depth += countChar(line, '{') - countChar(line, '}')

    if (!skipping) {
      kept.push(line)
    }

    if (depth <= 0) {
      depth = 0
      skipping = false
    }
  }

  const output = kept.join('\n').replace(/\n{3,}/g, '\n\n').trim()
  if (!output.includes('export interface') && !output.includes('export type')) {
    throw new CodegenError('No type declarations survived filtering. Check the --in directory.')
  }

  // Guard rather than trust. If the generated format changes, this stops the
  // run instead of writing types that only compile when `firebase` is
  // installed, which would be found much later and much further away.
  const leaked = WEB_SDK_TYPES.filter(name => new RegExp(`\\b${name}\\b`).test(output))
  if (leaked.length > 0) {
    throw new CodegenError(
      `Filtered types still reference web SDK types: ${leaked.join(', ')}. ` +
        'The generated SDK format changed; rn-sql-connect-codegen needs updating.',
    )
  }

  return output
}

const countChar = (value: string, char: string): number => {
  let count = 0
  for (const current of value) {
    if (current === char) {
      count += 1
    }
  }
  return count
}
