# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# rn-sql-connect takes Firebase from CocoaPods so that it shares the instance
# react-native-firebase configures. That means react-native-firebase must be in
# CocoaPods mode too: in SPM mode there would be two copies of FirebaseCore and
# Data Connect would never see the configured app.
# https://github.com/invertase/react-native-firebase/issues/9140
$RNFirebaseDisableSPM = true
$RNFirebaseAsStaticFramework = true

linkage = ENV['USE_FRAMEWORKS'] || 'static'
Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
use_frameworks! :linkage => linkage.to_sym

target 'RnSqlConnectExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
